### ISSUE TITLE
how to use api by postman

### ISSUE THREAD

**Issue by KuroshioDev** [jianxingxuejian/grasscutter-plugin#1]
![image](https://user-images.githubusercontent.com/40047545/198350601-8d713838-8eb3-4ccd-9438-9b914274a205.png)

i build the admin token by  /plugin/admin/auth?adminVoucher= and It is fail to create a account by this token

**Comment by jianxingxuejian** [comment]
The request header is admin_token.

**Comment by KuroshioDev** [comment]
> The request header is admin_token.
![image](https://user-images.githubusercontent.com/40047545/198694494-8a039064-e5a8-483f-8ca3-22beaf5b699d.png)

Hi, it not work, what is matter

**Comment by jianxingxuejian** [comment]
The parameters are in the request body.
![image](https://user-images.githubusercontent.com/39818150/198696664-77fa77c1-b7a6-431b-a97f-677b8c9a90f6.png)

**Comment by KuroshioDev** [comment]
> The parameters are in the request body. ![image](https://user-images.githubusercontent.com/39818150/198696664-77fa77c1-b7a6-431b-a97f-677b8c9a90f6.png)

thx you very much
